### ISSUE TITLE
Extend PublishEvent

### ISSUE THREAD

**Issue by Skarm** [centrifugal/centrifuge#104]
Good time of day.
Is it possible to add `StreamPosition` to a `PublishEvent`?

```
client.On().Publish(func(e centrifuge.PublishEvent) centrifuge.PublishReply {
...
offset := e.StreamPosition.Offset
...
}
```

**Comment by FZambia** [comment]
Hello, I suppose no, because this operation happens before message actually published to Engine.

**Comment by FZambia** [comment]
Which problem you want to solve btw?

**Comment by Skarm** [comment]
So that it's possible to get `StreamPosition` and use the values, for example, when writing to the database or something else.
In case of using the `node.Publish()`, the function will return StreamPosition.

Yes, with a callback can't get a `StreamPosition` in the current implementation...

**Comment by FZambia** [comment]
You can get Offset only after message published to engine, Publish callback called **before** actual publish so on this stage Offset is simply not available. Closing since I don't think we can do something here (and don't understand why we actually should).
