### ISSUE TITLE
 Chat_json example doesn’t work

### ISSUE THREAD

**Issue by SergeyDavidenko** [centrifugal/centrifuge#112]
Chat_json example doesn’t work, a0f7b998481c50dde5924487e7b344c9324ec06c commit.

`# command-line-arguments
cmd/main.go:94:3: unknown field 'HistoryMetaTTL' in struct literal of type centrifuge.MemoryEngineConfig
cmd/main.go:151:92: e.Method undefined (type centrifuge.RPCEvent has no field or method Method)
cmd/main.go:198:11: assignment mismatch: 2 variables but node.Publish returns 1 values`

go.mod

`
go 1.13

require (
	github.com/centrifugal/centrifuge v0.7.0
	github.com/prometheus/client_golang v1.6.0
)
`

**Comment by FZambia** [comment]
Hello, v0.7.0 does not have that field yet (it is available only in master branch at moment) - just don't use it in example.

**Comment by FZambia** [comment]
Released [v0.8.0](https://github.com/centrifugal/centrifuge/releases/tag/v0.8.0) - examples should properly work with it.
