### ISSUE TITLE
Swappable Persistence Backends?

### ISSUE THREAD

**Issue by stemcc** [centrifugal/centrifuge#12]
I'm curious if making the persistence backends swappable is on the roadmap for this library. 

In my specific use case, it would be nice to use the lightweight [Bolt](https://github.com/coreos/bbolt) for persistence while still utilizing centrifuge's pub sub system, unlike the way you have it set up with Redis now which seems to require using Redis's pub/sub system if you want persistence.

If there was an API for writing pluggable backends, I'd happily get started on one for bolt.

**Comment by FZambia** [comment]
Hello, my plan is making internal engine parts pluggable in the end. Though I am not sure about correct implementation and currently concentrated on finishing work on Centrifugo v2 built on top of this lib.

I don't fully understand your intents - this library should only persist a short-term cache of messages. What is you use case for persistent store? Are you going to keep unlimited amount of messages in it? Also Redis Pub/Sub is not currently used for persistence - it is used for Centrifuge node scalability.

**Comment by stemcc** [comment]
Great, I'm glad to hear that's on the roadmap. 

My use case for persistence is to have a cache that can survive reboots, while ideally using something a little simpler than Redis but that can still provide simple kv lookups (like Bolt for example).  Otherwise I would just write to a log file then load that into memory when the app comes back online).  I'm using Centrifuge to pass messages and data from a local daemon/server to a local gui client, local daemon to remote client, or remote daemon/server to local daemon/server.

**Comment by gedw99** [comment]
Badger or bolt with raft leader election should be enough to get HA.

I think redis is HA in that you can specify how often it syncs to disk ?

**Comment by gedw99** [comment]
Then use the event sourcing pattern.
Write to a boltdb bucket.
Have another process push it out to how many durable storage engines you
have.

This is why event sourcing exist imho.
Then the HA of your durable storage engines becomes not so important too.
As long as the event store is HA you can always recover. So an event store
based on boltdb raft is a good match.

The db and cache based on whatever. Tons of options with boltdb or badger.

**Comment by FZambia** [comment]
@gedw99 thanks for suggestions. Centrifuge lib in its current state is very close to event sourcing system. At least this is already kind of. Its hard to say at moment in what direction we should expand it - maybe the understanding will come with usage reports if any:)

**Comment by gedw99** [comment]
I guess it's also because your relying on redis to do the hard stuff which is totally understandable.

You could use emitter golang project instead of redis. Then you can wrap it. It uses mqtt as the messaging layer and supports scaling honizontally

**Comment by thienpow** [comment]
maybe can use mongodb instead of redis

**Comment by FZambia** [comment]
Guys, just want to update status on this. I remember about this issue but the task is not straightforward. I have some ideas but they ruin under various edge cases. At moment I am in progress of validating new idea - maybe it will fit fine but can't be sure.

At least I proved that I can make current engines separate if neseccary. Also played a bit with custom Nats engine which implements only PUB/SUB logic without any persistence layer.

**Comment by FZambia** [comment]
@stemcc please take a look at referenced pull request where I am trying to split Engine on three parts - Broker, HistoryManager and PresenceManager. This is a road to pluggable components, hope this will allow to do more with this library. At least look at [interesting concept example](https://github.com/centrifugal/centrifuge/tree/split_engine_sync_publish/examples/custom_broker) where Nats used for PUB/SUB and Redis for other stuff.

**Comment by FZambia** [comment]
Let's reopen until it will be documented

**Comment by FZambia** [comment]
Just posted a [note about pluggable components](https://medium.com/@fzambia/note-about-pluggable-components-in-centrifuge-library-fe7e34f7e0d7) on Medium, also we have [an example](https://github.com/centrifugal/centrifuge/tree/master/_examples/custom_broker) of setting custom broker implementation. I suppose this is enough for a moment. If there are any questions about current implementation - feel free to ask.
