### ISSUE TITLE
Decouple Centrifugo specific channel namespace configuration from library core

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge#128]
At moment Centrifuge library follows Centrifugo in terms of subscribe and publish permissions. While this is fine for Centrifugo - having namespaces and predefined channel rules inside a library can be a bit confusing for users.

What I want to achieve with this library is make it only a reasonable wrapper over client-server protocol without many **opinionated** logic on top of it. I.e. give developers a possibility to define their own channel rules and permission checks.

Another confusing thing in my opinion is that if we don't define `On().Subscribe()` handler then client will be able to subscribe on all channels. I believe the default behaviour should be: **not allow subscription at all if subscribe handler not set for connection**.

That said I'd want to decouple namespace and channel permission logic from Centrifuge library core since it adds a very opinionated layer to library. Maybe this process will also require decoupling JWT parsing logic too.

**Comment by masterada** [comment]
Can't wait for this. Can you make it so we can pass some kind of context for the client? Eg: context.Context that can be returned from ClientConnecting and we get it in ClientConnected, or maybe a simple map in the client object that can be freely modified in the Client object, or anything like that. During Subscribe, it would make it much simpler to use headers/host name/result of custom auth from ClientConnecting/etc.

**Comment by FZambia** [comment]
Context already propagates to ClientConnected handler and you can modify it in ClientConnecting - this will stay the same in new version. See https://github.com/centrifugal/centrifuge/blob/116c717b8f0dea4f43be63e1c9f47bd5634ae779/events.go#L20 - this is a modified context you can return to put some addition info to it. Is this what you mean or I did not understand right?

**Comment by masterada** [comment]
I missed that, cool. Looking forward to the changes then :)

**Comment by FZambia** [comment]
Merged #129 to master, hope to create v0.10.0 release tag tomorrow

**Comment by FZambia** [comment]
Done in v0.10.0
