### ISSUE TITLE
command ID required for commands with reply expected

### ISSUE THREAD

**Issue by rocc0** [centrifugal/centrifuge#13]
I want to mock centrifugo for unit tests and i stucked on this error:
` command ID required for commands with reply expected: map[client:7e9210d6-24ca-4508-b977-9c0a4fe0f61d user:]`
Error can be reproduced with this server https://github.com/centrifugal/centrifuge/tree/master/examples/chat_json and this client https://github.com/centrifugal/centrifuge-go/blob/master/examples/private.go, with some correction of course. Dockerized centrifugo working perfectly. How to solve this error? Thanks.

**Comment by FZambia** [comment]
Hello @rocc0 !

Go client is not released yet, the version that works with this lib located in [c2 branch](https://github.com/centrifugal/centrifuge-go/tree/c2)

**Comment by FZambia** [comment]
Hope the problem solved, reopen if not.
