### ISSUE TITLE
redis presence auto extend the expiration time

### ISSUE THREAD

**Issue by larry-dev** [centrifugal/centrifuge#131]
@FZambia  Hi
i upgrade centrifuge to v0.9.0.
Why doesn't "redis presence data" renew automatically
I don't know what to do now.

**Comment by FZambia** [comment]
Have you looked at v0.9.1? It has presence related fix, if it does not help - please provide more information about problem.

BTW, Also look at #129 - huge changes coming, I am removing namespaces and JWT from this lib (but it will be possible to add the same on top of course)

**Comment by larry-dev** [comment]
i will try it.   thx.    This is a good idea, but I recommend that the setToken method be retained.The authentication of token is given to the user

**Comment by FZambia** [comment]
Yes, that's the idea - I dont want to touch client-server protocol at all (and I have no plans to change it later even for v1 release if it happen) and its possibilities will be the same. Users will be able yo use own permissions and own token parsing logic.

**Comment by larry-dev** [comment]
That's how I use it now.

```
if e.Token == "" {
		//reply.Error = common.NewError("用户token为空")
		return
	}
	var err error
	data, err := h.TokenT.Valid(e.Token)
	if err != nil {
		reply.Disconnect = centrifuge.DisconnectInvalidToken
		return
	}
```

**Comment by larry-dev** [comment]
@FZambia  i use centrifuge to write game server. but I want to know if a user still has a connection in  channel. Do you have any good idea?

**Comment by FZambia** [comment]
Cant say without more information, join our chat rooms in Telegram or Discord, will be nice to hear more about your use case

**Comment by FZambia** [comment]
Closing since nothing actionable left here. @larry-dev please reopen with **detailed** description if the problem remains.
