### ISSUE TITLE
is there possible to transfer binary file stream through ws of centrifuge

### ISSUE THREAD

**Issue by xurwxj** [centrifugal/centrifuge#14]
is there possible to transfer binary file stream through ws/wss transport of centrifuge

**Comment by FZambia** [comment]
@xurwxj hi! It was not designed for file streaming, though it can be possible as you can pass arbitrary bytes in protobuf payload. Personally I had no experience with file streaming so this needs investigation. If you end up with something - please share.

**Comment by xurwxj** [comment]
@FZambia thanks. I'll share when done with something
