### ISSUE TITLE
How do i add jwt tokens on channel or rooms in javascript client and server

### ISSUE THREAD

**Issue by junaidy-johm** [centrifugal/centrifuge#151]
Sorry my bad english.
I am confused because poor of tutorial example in youtube.
I am confused between token for client and token for server centrifuge like this:

```
var centrifuge = new Centrifuge('ws://centrifuge.example.com/connection/websocket');

centrifuge.setToken(YOUR_TOKEN);

centrifuge.subscribe("news", function(message) {
    console.log(message);
});

centrifuge.connect();
```

How do i add token jwt in javascript client
```
var centrifuge = new Centrifuge('ws://centrifuge.example.com/connection/websocket');

centrifuge.subscribe("news", function(message) {
    console.log(message);
});

centrifuge.connect();
```

**Comment by FZambia** [comment]
Hello, I know that the documentation for this library is pretty poor, my main focus is on Centrifugo server at this moment, hopefully in the future docs for this library will be improved.

I don't fully understand your question, could you please ask a more concrete one?

Also, [we have an example](https://github.com/centrifugal/centrifuge/tree/master/_examples/jwt_token) here for JWT – have you seen it? Maybe it covers your question.

**Comment by FZambia** [comment]
Closing since no response from op, feel free to reopen with more details.
