### ISSUE TITLE
how to get the client ip?

### ISSUE THREAD

**Issue by make3782** [centrifugal/centrifuge#190]
how to get the client ip?  i can't find any method to get the client ip, tks.

**Comment by FZambia** [comment]
Hello, you can put client IP into context inside middleware and retrieve it later.

```go
func getIP(r *http.Request) string {
	...
}

func ipMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ip := getIP(r)
		newCtx := context.WithValue(r.Context(), ipKey, ip)
		h.ServeHTTP(w, r.WithContext(newCtx))
	})
}
```

**Comment by make3782** [comment]
> Hello, you can put client IP into context inside middleware and retrieve it later.
> 
> ```go
> func getIP(r *http.Request) string {
> 	...
> }
> 
> type ipKey struct{}
> 
> func ipMiddleware(h http.Handler) http.Handler {
> 	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
> 		ip := getIP(r)
> 		newCtx := context.WithValue(r.Context(), ipKey{}, ip)
> 		h.ServeHTTP(w, r.WithContext(newCtx))
> 	})
> }
> ```

tks
