### ISSUE TITLE
Unknown Redis command called from Lua script

### ISSUE THREAD

**Issue by make3782** [centrifugal/centrifuge#191]
I subscribed two channels to a user, using redis broker, and k8s. When the service restarts, the client cannot automatically reconnect after the client is disconnected. I checked the server log and reported the following error:

> {"env":"develop","level":"info","msg":"[centrifuge] client connection established: map[client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 transport:websocket]","time":"2021-04-11 00:19:38.760"}
{"env":"develop","level":"info","msg":"[centrifuge] client authenticated: map[client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 user:4072698]","time":"2021-04-11 00:19:38.778"}
{"env":"develop","level":"info","msg":"[centrifuge] error on recover: map[channel:channel:teachers client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 error:ERR Error running script (call to f_a8e5c3b612afd49c877994af2c3d4a99c693fb58): @user_script:20: @user_script: 20: Unknown Redis command called from Lua script  user:4072698]","time":"2021-04-11 00:19:38.780"}
{"env":"develop","level":"info","msg":"[centrifuge] error on recover: map[channel:teachers#4072698 client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 error:ERR Error running script (call to f_a8e5c3b612afd49c877994af2c3d4a99c693fb58): @user_script:20: @user_script: 20: Unknown Redis command called from Lua script  user:4072698]","time":"2021-04-11 00:19:38.780"}
{"env":"develop","level":"info","msg":"[centrifuge] disconnect after handling command: map[client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 command:id:78 params:\"{\\\"token\\\":\\\"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9hcGkucmlzZW9uLmxvY2FsXC9ncmFwaHFsXC9ub2F1dGgiLCJpYXQiOjE2MTc4ODI1MDYsImV4cCI6MTYyNDM2MjUwNiwibmJmIjoxNjE3ODgyNTA2LCJqdGkiOiJCRkFHVVJwSnA0eUxzUUd5Iiwic3ViIjo0MDcyNjk4LCJwcnYiOiIyM2JkNWM4OTQ5ZjYwMGFkYjM5ZTcwMWM0MDA4NzJkYjdhNTk3NmY3In0.yChEXRTbHrn5UShSxnjnk-wmI6xr8M8ghLKVDAQSWWA\\\",\\\"subs\\\":{\\\"channel:teachers\\\":{\\\"recover\\\":true,\\\"epoch\\\":\\\"1618070389\\\"},\\\"teachers#4072698\\\":{\\\"recover\\\":true,\\\"epoch\\\":\\\"1618070389\\\"}}}\"  reason:internal server error user:4072698]","time":"2021-04-11 00:19:38.780"}
{"env":"develop","level":"info","msg":"[centrifuge] client connection completed: map[client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 duration:19.991579ms transport:websocket]","time":"2021-04-11 00:19:38.780"}
{"env":"develop","level":"info","msg":"[centrifuge] closing client connection: map[client:380e5fdd-73fb-4cd4-a0a8-b9a2449a64f1 reason:internal server error reconnect:true user:4072698]","time":"2021-04-11 00:19:38.781"}

The related logic of the server program is like this:
```go
	node.OnConnecting(func(ctx context.Context, e centrifuge.ConnectEvent) (centrifuge.ConnectReply, error) {
		claims, err := internal.VerifyToken(e.Token)
		if err != nil {
			return centrifuge.ConnectReply{}, errors.WithMessagef(err, "[teacherWebSocketServer.OnConnecting] jwt验证错误")
		}
		uid := int32(claims.(jwt.MapClaims)["sub"].(float64))
		uidString := fmt.Sprintf("%d", uid)
		if uid <= 0 {
			return centrifuge.ConnectReply{}, errors.New("[teacherWebSocketServer.OnConnecting] jwt验证错误: uid错误")
		}
		return centrifuge.ConnectReply{
			Credentials: &centrifuge.Credentials{
				UserID:   uidString,
				ExpireAt: int64(claims.(jwt.MapClaims)["exp"].(float64)),
			},
			Subscriptions: map[string]centrifuge.SubscribeOptions{
				"teachers#" + uidString: {JoinLeave: true, Recover: true, Presence: true},
				"channel:teachers":      {JoinLeave: true, Recover: true, Presence: true},
			},
		}, nil
	})
```

**Comment by FZambia** [comment]
Please provide steps to reproduce - I quickly tested this and reconnect works fine for me. Also Redis version and Redis broker config can be useful.

**Comment by FZambia** [comment]
@make3782 I bet you are using Redis < 5 right?

**Comment by make3782** [comment]
> @make3782 I bet you are using Redis < 5 and have `UseStreams: true` in Broker config right?

You are right, I use redis 4, the broker configuration is like this:
```go
	redisShardConfigs := []centrifuge.RedisShardConfig{
		{Address: fmt.Sprintf("%s:%s", redisconf["HOST"], redisconf["PORT"]), Password: redisconf["PASSWORD"], DB: db_number},
	}
	var redisShards []*centrifuge.RedisShard
	for _, redisConf := range redisShardConfigs {
		redisShard, err := centrifuge.NewRedisShard(node, redisConf)
		if err != nil {
			log.Fatalf("[teacherWebSocketServer] 创建NewRedisShard错误: %s", err)
		}
		redisShards = append(redisShards, redisShard)
	}

	broker, err := centrifuge.NewRedisBroker(node, centrifuge.RedisBrokerConfig{
		Prefix:     REDIS_PERFIX,
		UseStreams: true,
		Shards:     redisShards,
	})
	if err != nil {
		log.Fatalf("[teacherWebSocketServer] 创建redis broker错误: %s, %#v", err, broker)
	}
	node.SetBroker(broker)

	presenceManager, err := centrifuge.NewRedisPresenceManager(node, centrifuge.RedisPresenceManagerConfig{
		Prefix: REDIS_PERFIX,
		Shards: redisShards,
	})
	if err != nil {
		log.Fatalf("[teacherWebSocketServer] 创建redis NewRedisPresenceManager错误: %s", err)
	}
	node.SetPresenceManager(presenceManager)
```

**Comment by FZambia** [comment]
So Redis STREAM data structure only available since Redis v5. I added commit that checks whether streams supported on start - see #192 - should make things clear.

You have two options:
1) Upgrade Redis to version >= 5
2) Disable `UseStreams` - in this case history will be kept in LIST data structure. This has some performance downsides but for streams with retention < 100 publications lists should perform well enough.
