### ISSUE TITLE
Message delivery ACK

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifuge#20]
Does this support delivery ACK ?

My use case is that a user has many devices and I want to know that it was delivered to one of those devices AND cancel the delivery to their other devices.
So this use case is really only for notifications.

**Comment by FZambia** [comment]
Hi! No, acks are not supported. When history used every publication in channel stream has it's own incremental sequence and client can pass last received sequence to server to recover missed messages on resubscribe. I don't know how to implement delivery cancelling in terms of this library - as it has PUB/SUB semantics - with no queueing concepts.

**Comment by FZambia** [comment]
So, originally the idea of this library is massive PUB/SUB when many connections want all messages from channels they subscribed to. @gedw99 please reopen if you still have questions regarding to this.

**Comment by gedw99** [comment]
Thanks for all the explanation.
I think the way it is is fine.

I guess it's just a matter of the client remembering the last sequence it
processed and all is good.
