### ISSUE TITLE
Redis engine TLS support

### ISSUE THREAD

**Issue by vitoordaz** [centrifugal/centrifuge#23]
Hello,

I'm wondering if you are planning (or maybe it's already implemented) to add a support for redis TLS. Looks like it's supported by redigo.

I think this would be really valuable feature.

I'm willing to make a PR for this feature.

**Comment by FZambia** [comment]
Hello @vitoordaz , do you have a real use case for this? Do you use an TLS-terminating proxy between client and Redis (as Redis does not support TLS connections itself AFAIK)?

**Comment by vitoordaz** [comment]
@FZambia Yes I do. For example if you use AWS elastic cache it recommends to use TLS https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/encryption.html

**Comment by vitoordaz** [comment]
I've made a pull request for centrifuge part of changes https://github.com/centrifugal/centrifuge/pull/24

**Comment by vitoordaz** [comment]
PR #24 was merged
