### ISSUE TITLE
Redis broker pool size

### ISSUE THREAD

**Issue by anhnguyensgu** [centrifugal/centrifuge#258]
I have set up the package to handle the real-time message and it works perfectly. However, I am so curious about the pool size configuration for Redis broker. After taking a look at the code Redis_shard.go, I found that Redis broker takes the default pool size 128. 

Do we have a way to configure the pool size?

**Comment by FZambia** [comment]
Hello, @anhnguyensgu! 

There are 3 modes in current Redis broker implementation:

1. Standalone Redis
2. Redis with Sentinel
3. Redis Cluster

For cases 1 and 2 pool size does not really matter - we utilize Redis pipelining and only several active connections from Centrifuge to Redis are active at any point of time.

I think pool size only matters in Redis Cluster case - where we are using pool to issue most of commands except publish without history.

I think in the near future Centrifuge Redis implementation [may migrate from `redigo` to `go-redis`](https://github.com/centrifugal/centrifuge/pull/235) or possibly to `rueidis` library - and those allow using pipelining for communication with Redis Cluster too. Pool size should not be too important in that case I believe.

So I think we should not expose pool size at this point. Do you have issues with current default  pool size (which I think may happen only in Redis Cluster scenario)? If yes -  we can address it more precisely, possibly looking how `go-redis` from the mentioned pull request behaves - I think it should provide better overall throughput.

**Comment by FZambia** [comment]
We migrated to rueidis library in #262 – where connection pool does not have much sense anymore, Centrifuge will use pipelining over several connections for all operations. So I suppose this issue can be closed.

**Comment by FZambia** [comment]
The draft of blog post about rueidis migration: https://github.com/centrifugal/centrifugal.dev/pull/18 - @anhnguyensgu probably you will be interested to check it
