### ISSUE TITLE
reporting node health

### ISSUE THREAD

**Issue by flaviamissi** [centrifugal/centrifuge#27]
How is node health reported? Looked around in the code and couldn't see anything obvious.

[centrifugo](https://github.com/centrifugal/centrifugo)'s api has no healthcheck endpoint, while investigating how to create one I noticed that health would need to be reported by each node. Is that correct?

To start simple we could just ping the configured engine, then report "ok" or "not ok".

I'm willing to send a PR, but would probably need a little guidance to  get me started.

Great project btw.
Thanks!

**Comment by FZambia** [comment]
Hello, could you provide a bit more background on why do you need this? Is this for Kubernetes or smth similar?

Also do you need this per node or per full setup (i.e. switch to another Centrifugo setup on balancer for example)?

Not sure at moment which information I should provide to you as I don't understand what do you mean under `node health` in this moment.

**Comment by flaviamissi** [comment]
Hey, yes of course.

> Is this for Kubernetes or smth similar?

Exactly, I deployed it to multiple environments in kubernetes and I'm currently using the admin `/` endpoint as healthcheck, but it's not suitable for all my envs and it isn't a very trust worthy one either.

> Also do you need this per node or per full setup (i.e. switch to another Centrifugo setup on balancer for example)?

I was envisioning something more like _per container_, so if a container would for example loose access to redis for any reason, the healthcheck would start failling and kubernetes (or any other similar tool) could find this out via healthcheck then re-kick the problematic container.

Hope this is more clear now, thanks for the quick answer.

**Comment by FZambia** [comment]
First idea here is adding health status change in [here](https://github.com/centrifugal/centrifuge/blob/master/node.go#L207) - this is a place when node tries to send information about itself to other nodes. This is done periodically and if this operation fails - engine is not working.

But this won't properly work in case when Redis sharding used at moment as we try to deliver Control message [using each Redis shard in order](https://github.com/centrifugal/centrifuge/blob/master/engine_redis.go#L470), so actually some of them can return error.

So if we want to check all shards this feature requires new `Health` method in engine which will return health status taking into account all shards and any engine specific things.

**Comment by flaviamissi** [comment]
> But this won't properly work in case when Redis sharding used at moment as we try to deliver Control message [using each Redis shard in order](https://github.com/centrifugal/centrifuge/blob/master/engine_redis.go#L470), so actually some of them can return error.

Is this really something this healthcheck should be concerned about thought? On a cluster installation (a redis cluster in this case), node failures are acceptable _as long as the whole cluster is still operational_.

> Looks like if we want to check all shards this feature requires new Health method in engine which will return health status taking into account all shards and any engine specific things.

Checking the health of each and every shard sounds like something redis should be doing, not centrifuge. There's even a command for that on `redis-cli`: [`redis-cli --cluster check 127.0.0.1:7000`](https://redis.io/topics/cluster-tutorial). I think an exposed ping (or health) method in the engine should be enough. Then the `Node` would expose a status check method. 

Thoughts?

**Comment by FZambia** [comment]
> Is this really something this healthcheck should be concerned about thought? On a cluster installation (a redis cluster in this case), node failures are acceptable as long as the whole cluster is still operational.

Centrifuge uses application-level sharding (not Redis cluster). Because PUB/SUB does not scale well in Redis cluster - https://github.com/antirez/redis/issues/2672. So we have to manually check each shard. Does it make sense?

Yep, the `Node` must have `Health` method too of course. Btw - look at [related pr](https://github.com/centrifugal/centrifugo/pull/253) I opened recently - it waits for this method to be implemented in this lib.

**Comment by flaviamissi** [comment]
> Centrifuge uses application-level sharding (not Redis cluster). Because PUB/SUB does not scale well in Redis cluster - [antirez/redis#2672](https://github.com/antirez/redis/issues/2672) and [Redis mailing list](https://groups.google.com/forum/#!topic/redis-db/B0_fvfDWLGM). So we have to manually check each shard. Does it make sense?

Oh that explains it, it does make sense, thank you.



> Yep, the `Node` must have `Health` method too of course. Btw - look at [related pr](https://github.com/centrifugal/centrifugo/pull/253) I opened recently - it waits for this method to be implemented in this lib.

Great news! I see the PR is merged now, do you have any kind of time line for when this should be generally available?

Thanks for making it happen btw 🎉

**Comment by FZambia** [comment]
It's already available in Centrifugo v2.1.0 - but it just provides health endpoint without doing extra checks inside engine - i.e. here is a [healthcheck handler](https://github.com/centrifugal/centrifugo/blob/master/internal/health/health.go#L28). If you need more than that we still have to do this inside this lib first.

**Comment by flaviamissi** [comment]
This satisfies my current needs, thank you!

**Comment by FZambia** [comment]
OK, great! Will close this issue then because my current needs also satisfied with that simple health checker, if you will need more from it feel free to reopen!
