### ISSUE TITLE
private channel

### ISSUE THREAD

**Issue by aminNazarii** [centrifugal/centrifuge#272]
i didn't find any way to private channel in new version. could you introduce a reference that help me how can use private channels?

**Comment by FZambia** [comment]
Hello @aminNazarii , which version you had? Private channels were removed from this lib two years ago. So you are on v0.9.x?

**Comment by aminNazarii** [comment]
@FZambia i used old version that support refresh and auth request automatically. in new version i used token way and work successfully. 
thank you
