### ISSUE TITLE
Client level heartbeat config

### ISSUE THREAD

**Issue by bfwbbrj** [centrifugal/centrifuge#282]
Hi, I'm wondering if you guys have any plan to support client level ping config?

**Comment by FZambia** [comment]
Hello @bfwbbrj 

No such plans. Do I understand right you mean [setting this struct](https://github.com/centrifugal/centrifuge/blob/5dc334049fc6cc7c923b7871d0737937dba3c699/handler_websocket.go#L73) on individual connection level, i.e. as part of [ConnectReply](https://github.com/centrifugal/centrifuge/blob/5dc334049fc6cc7c923b7871d0737937dba3c699/events.go#L34)? Based on which criteria? What is the use case?

**Comment by bfwbbrj** [comment]
> Hello @bfwbbrj
> 
> No such plans. Do I understand right you mean [setting this struct](https://github.com/centrifugal/centrifuge/blob/5dc334049fc6cc7c923b7871d0737937dba3c699/handler_websocket.go#L73) on individual connection level, i.e. as part of [ConnectReply](https://github.com/centrifugal/centrifuge/blob/5dc334049fc6cc7c923b7871d0737937dba3c699/events.go#L34)? Based on which criteria? What is the use case?

I'm currently building a service that will provide real-time message functionalities to other services. And each of those service need to have a custom connection timeout(i.e the ping/pong interval). From what I read in the websocket implementations, the ping/pong interval can only be set on the app level or the transport level. So it'd be great if I can set the ping/pong interval for each client(connection) in the ConnectReply.

**Comment by bfwbbrj** [comment]
Another question. From my understanding, unidirectional client means that they can only receive message from server side and not vice versa, is this correct? I'm asking this because, for some reasons, I can only use c# in client side. And it seems that there's no c# client sdk provided. Thanks!

**Comment by FZambia** [comment]
> I'm currently building a service that will provide real-time message functionalities to other services. And each of those service need to have a custom connection timeout(i.e the ping/pong interval).

But why? I understand you need this from your first message, I am curious why exactly this is necessary in your case?

> Another question. From my understanding, unidirectional client means that they can only receive message from server side and not vice versa, is this correct? I'm asking this because, for some reasons, I can only use c# in client side. And it seems that there's no c# client sdk provided.

Yeah... Unfortunately we don't have C# SDK - this is a very popular request from the community, hope it will be available at some point, definitely first in the queue. You are right about unidirectional clients, you can read some Centrifugo docs BTW which may be considered as some extra doc for Centrifuge lib:

* https://centrifugal.dev/docs/transports/overview#unidirectional
* https://centrifugal.dev/docs/transports/uni_websocket
* https://centrifugal.dev/docs/transports/uni_http_stream
* https://centrifugal.dev/docs/transports/uni_sse

**Comment by bfwbbrj** [comment]
@FZambia 

> But why? I understand you need this from your first message, I am curious why exactly this is necessary in your case?
> 
This is because I'm building a multi-tenant service, and each of tenant will need to have their own timeout intervals. Suppose we have a chat service and an online game service as tenants of my service, the timeout interval of the game will probably need to be shorter than the chat's. Since they are all connected to the same server(s), if connection level timeout interval is not customerizable, all connections from the chat and the game will share the same timeout, which could potentially lead to something bad. I can work around this by dynamically creating new server with different configuration when new connection arrives or implement my own heartbeat on top of centrifuge. But either of these would require some extra work that's not trivial. So I really hope you guys can add the option to set individual connection's timeout interval. 


>https://centrifugal.dev/docs/transports/overview#unidirectional
>https://centrifugal.dev/docs/transports/uni_websocket
>https://centrifugal.dev/docs/transports/uni_http_stream
>https://centrifugal.dev/docs/transports/uni_sse
>Centrifuge does not have built-in unidirectional transport implementation - we only provide a way to build such type of >transport on top of Centrifuge (what Centrifugo server does actually). And we have some examples here – but better to >look at Centrifugo source code, for example [for unidirectional HTTP streaming]>>(https://github.com/centrifugal/centrifugo/tree/master/internal/unihttpstream)

Thanks! I will start building my own client from here.
