### ISSUE TITLE
High memory consumption

### ISSUE THREAD

**Issue by 0michalsokolowski0** [centrifugal/centrifuge#291]
**Describe the bug**
Hey, 
When running the server memory consumption is continuously growing until the service is restarted.
We use Redis as storage, and the latest version of `github.com/centrifugal/centrifuge` (0.29.0), we've had the issue since (0.25.0). 

To me, it looks like goroutines are not correctly handled in centrifugal (I am sending the pprof screenshot below).
Could you help me understand why it's happening and how it can be fixed?

**To Reproduce**
1. Run server for a day having thousands of connections
2. Memory is continuously increasing

**Expected behavior**
Memory consumption is stable.

**Screenshots**
pprof of goroutines

![pprof](https://user-images.githubusercontent.com/53563914/233350214-da680da7-a645-48c0-924b-c30408acf210.png)

**Versions (please complete the following information):**
 - OS: [e.g. MacOS] (not applicable)
 - Client SDK version [centrifuge-dart latest] 
 - Server version [0.29.0]

**Comment by FZambia** [comment]
Hello @0michalsokolowski0 

Thanks, I'll look. If you can find a local reproducer meanwhile - it will help.

**Comment by FZambia** [comment]
Do you mean BTW that before 0.25.0 release there were no issue with memory consumption?

**Comment by FZambia** [comment]
Also, if you can upload the outputs of `/debug/pprof/goroutine?debug=1` and `/debug/pprof/goroutine?debug=2` - it may help to detect the source of the leak. And maybe entire memory profile picture (not cropped on the top).

**Comment by FZambia** [comment]
@0michalsokolowski0 hello, any update here? I tried to reproduce using various load profiles combining disconnections/messages - but have not been able to reproduce. So more information required – reproducer, minimal program which shows your usage pattern, goroutine profiles mentioned above - probably this happens under some specific Centrifuge usage/configuration which I am missing.

**Comment by FZambia** [comment]
@0michalsokolowski0 glad it solved, will appreciate if you post more details - how it was and how it should be, probably it will help someone in the future or will point me to improve docs or examples.
