### ISSUE TITLE
How Many Concurrent RPC Requests can server handle?

### ISSUE THREAD

**Issue by developerpaaji** [centrifugal/centrifuge#359]
We have a requirement where we have a game where at end of each level user sends some input. While load testing with 20k users we saw that we are getting RPC timeout error. So many how can we handle this type of traffic at centrifuge server

**Comment by FZambia** [comment]
Hello, @developerpaaji 

You ask about performance without any details and benchmarking code. I tested with one million clients and Redis engine without any timeouts. See https://centrifugal.dev/blog/2020/02/10/million-connections-with-centrifugo. Every load profile is different, so it's impossible to give advice here without understanding all the details and see the benchmark.

**Comment by FZambia** [comment]
Closing, I suggest writing a bench with your real load profile - if you see Centrifuge is not capable to handle it – you may think about scaling Centrifuge nodes - it's possible with built-in Redis engine, or maybe use many Centrifuge nodes with memory engine (if your goal is only to use RPC-s over websocket without need in PUB/SUB).

But I can not provide exact numbers as answer here. It depends.
