### ISSUE TITLE
Support tags on Publish()

### ISSUE THREAD

**Issue by heiningair** [centrifugal/centrifuge#398]
**Is your feature request related to a problem? Please describe.**
Right now it is not possible to make use of the tags feature using the golang library.

**Describe the solution you'd like**
When using the Publish() method on the Subscription, then I want to be able to pass optional tags for which i can resolve later in the publication handler.

It seems to be already builtin to the protocol. Is there a specific reason why it is not implemented in the golang library. Or is there another way to use the feature which I am not aware of?

thx

**Comment by FZambia** [comment]
Hello @heiningair 

Do you mean https://github.com/centrifugal/centrifuge-go ?

Seems a duplicate of https://github.com/centrifugal/centrifuge-go/issues/87

**Comment by heiningair** [comment]
@FZambia Thanks for the hint.. You are absolutely right! This is a duplicate then. The other one answers my question
