### ISSUE TITLE
"ENTER" rather than "Enter" in check for keyup value in tutorial example on README.md 

### ISSUE THREAD

**Issue by mdmeacham** [centrifugal/centrifuge#407]
**Describe the bug**
On README.md on https://github.com/centrifugal/centrifuge, the example index.html has a check for which key is used in the input element.   

The current javascript has if (e.key === "ENTER") with uppercase ENTER

Should be if (e.key === "Enter")

Causes example index.html to not react to user input

**To Reproduce**
1. Follow tutorial and see that user input in browser does not send message

**Expected behavior**
Pressing enter on input element causes message to be sent

**Comment by FZambia** [comment]
Hello @mdmeacham 

Many thanks for the report - just fixed. I guess there were some people who stopped looking at the library after the readme example failure 🫤
