### ISSUE TITLE
Publish message directly to Redis

### ISSUE THREAD

**Issue by voodoo-dn** [centrifugal/centrifuge#408]
Hi!

I develop messenger app and think about following integration:

Kafka topic contains messages, Kafka consumer receives message and publishes to Redis, Centrifugo nodes get messages from Redis and deliver to the client.

As I understood, such function is not available out of the box?

Thanks!

**Comment by FZambia** [comment]
Hello @voodoo-dn 

Yes, there is no such functionality, the communication layer between Centrifuge and Redis in internal implementation detail. Technically it's possible to publish in Redis channels in the format Centrifuge node expects, but the message format may change on that level and Centrifuge features like history cache won't be available.

> Kafka topic contains messages, Kafka consumer receives message and publishes to Redis, Centrifugo nodes get messages from Redis and deliver to the client.

I suggest changing this to: Kafka topic contains messages, Kafka consumer receives message and publishes to Centrifuge using Node.Publish (probably implement HTTP endpoint for this), Centrifuge nodes get messages from Redis and deliver to the client.

P.S. I am answering on question assuming you are using THIS library for your app, not https://github.com/centrifugal/centrifugo server. If you are using Centrifugo - then publish API already there.
