### ISSUE TITLE
broker example not displaying web gui

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifuge#42]
see:
https://github.com/centrifugal/centrifuge/blob/master/_examples/custom_broker/main.go#L137

I just get a browser list of files at localhost:8000
- sure nothing else is running :)

Reprod:

````
# nats
gnatsd

---

## redis
ln -sfv /usr/local/opt/redis/*.plist ~/Library/LaunchAgents  # Enable Redis autostart

launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist  # Start Redis server via launchctl
# homebrew.mxcl.redis.plist contains reference to redis.conf file location: /usr/local/etc/redis.conf 

redis-server /usr/local/etc/redis.conf # Start Redis server using configuration file, Ctrl+C to stop
redis-cli ping # Check if the Redis server is running

launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.redis.plist # Disable Redis autostart


---


# broker example
GO111MODULE=on
cd ./_examples/custom_broker && go run main.go

````

**Comment by FZambia** [comment]
Admin GUI is only available in Centrifugo. In examples we only serve dir for static assets to make example work in browser. It's possible to add admin GUI on top of this lib in the same way as it is implemented in Centrifugo but it was not supposed to work here.

**Comment by gedw99** [comment]
Then its not easy to develop on this.

1. Centrifugo is using port 8000 and yes you get an admin gui.
2. But the examples also use port 8000. But they cant have a gui at all. In fact not event logs.

SO stuck between a rock and a hard place. 

You said "It's possible to add admin GUI on top of this lib in the same way as it is implemented in Centrifugo but it was not supposed to work here." Then honestly i have to say, why dont you set it up  this way so people can develop on this ? 

Here is the minimum i need to develop against:
-  the centrifuge/_example/chat_protobuf example
- the Dart Chat example.

I cant even get this running with visible output, then its pretty hard to move on to testing NATS Broker.

**Comment by gedw99** [comment]
For anyone using gomodules you can can get the CHat server running using:

```
cd /Users/apple/workspace/go/src/github.com/centrifugal/centrifuge/_examples/chat_protobuf && GO111MODULE=on go run main.go
```

But the web gui does not work

**Comment by gedw99** [comment]
closing as another issue is more relevant now.
https://github.com/centrifugal/centrifuge/issues/43
