### ISSUE TITLE
Get the Admin GUI and Example(s) running at the same time

### ISSUE THREAD

**Issue by gedw99** [centrifugal/centrifuge#43]
At the moment it is hard to run an example and then see whats going on.
So having the Admin GUI run at the same time is a good start.

Here is my suggestion for what we need to do:
1. Get Admin GUI running with an example.
2. Use chat-Protobuf as the example.

- BTW the Web gui does not work for the Chat_protobuf example.
- I tracked the issue down to caching. Had to turn off caching when dev tools is open just to keep working.

---
Optional but just putting it here for now :)
How to have all examples running at the same time:
https://github.com/pion/webrtc/tree/master/examples
Its just an idea. Maybe for the next iteration of this issue if we feel its helpful. Might not too.

**Comment by FZambia** [comment]
@gedw99 hi, just look through code used in Centrifugo to embed web interface and realized that adding it to Centrifuge library is not as simple as I told you. There is a lot of boilerplate that we need to copy paste to make it work. This is still possible but I was expecting it to be much more simple - just forgot several implementation details.

For example admin handlers [depends on extra package](https://github.com/centrifugal/centrifugo/blob/master/internal/admin/handlers.go#L9) `api` which is also internal in Centrifugo.

It's generally possible to move that API part of Centrifugo into separate module.

**Comment by FZambia** [comment]
To prevent hanging issues – I have no time to integrate Centrifugo admin interface with Centrifuge library - it's not a simple thing and I don't think it is worth it at moment. Closing.
