### ISSUE TITLE
Centrifuge with 16S database

### ISSUE THREAD

**Issue by LaraUrban** [centrifugal/centrifuge#49]
Hi,

I was wondering if you could help us with the following problem that we encounter when using Centrifuge classification: We wanted to classify our 16S rRNA reads sequence by Oxford Nanopore, and used Centrifuge and Kraken2 to do so while building a NCBI database based on all bacterial data and a 16S database based on the Silva database for both classification tools. 
Whereas Kraken2 is able to classify most reads (>90%) with both bacterial NCBI and 16S database, Centrifuge only classifies comparably many reads if we take the bacterial NCBI database. In the case of the 16S database, very few reads (~10%) can be classified. I was wondering if you have any explanation for this effect? 

Many thanks for your help!

Best regards,
Lara

**Comment by FZambia** [comment]
@LaraUrban hello, this project is about real-time messaging - it does not have any relation to classification problems, I suppose you need to report somewhere else.
