### ISSUE TITLE
How to publish and subscribe to multiple channels?

### ISSUE THREAD

**Issue by nitin302** [centrifugal/centrifuge#50]
Hello, I'm currently working on a use-case wherein:

1) a client should be able to publish to one or more channels (at the same time) and a subscriber should be able to subscribe to one or many channels (at the same time).
2) publish to all subscribers without a client publish. Something like a PUT call with the channel name and the message to publish.

Is this possible? Any directions for this use-case?

Also, I see two handers NewWebsocketHandler and NewSockjsHandler. is WebsocketHandler a pure websocket handler with no means to downgrade to other methods where WS is not supported? So, if thats the case do you suggest using SockjsHandler in these scenarios?

**Comment by FZambia** [comment]
Hi @nitin302 

> a client should be able to publish to one or more channels (at the same time) and a subscriber should be able to subscribe to one or many channels (at the same time).

Do you experience any problem with this point? I suppose it's the main use case of library.

> publish to all subscribers without a client publish. Something like a PUT call with the channel name and the message to publish.

You can implement your own handler and call `node.Publish(channel, data)` which will publish data into channel without any client involved.

> Also, I see two handers NewWebsocketHandler and NewSockjsHandler. is WebsocketHandler a pure websocket handler with no means to downgrade to other methods where WS is not supported? So, if thats the case do you suggest using SockjsHandler in these scenarios?

Yeah, you understand right. If you need fallback then you have to use SockjsHandler and additionally import SockJS library in browser. I suppose you can somehow try to connect to raw Websocket endpoint first and start using SockJS only if request failed but it's not supported natively by our Javascript-client. From our native iOS and Android libs you can only connect to raw Websocket endpoint (as SockJS supported only by Javascript library).

**Comment by nitin302** [comment]
Hello. Thank you for the quick reply.

I think with https://github.com/centrifugal/centrifugo/blob/master/internal/api/api.go#L63 as a reference, I should be able to achieve this on the publisher side (to send data to one or many channels). Thank for mentioning the same.

For subscription however, I tried with https://github.com/centrifugal/centrifuge/blob/master/_examples/chat_json/index.html#L74 to subscribe to many channels with the same "sub" variable. I tried to loop with multiple channels.
It subscribes to only the last channel in the list. 

Do we need multiple "sub" variables (or an array / list) to subscribe to multiple channels?

**Comment by FZambia** [comment]
Yeah, just call `centrifuge.subscribe()` several times. https://github.com/centrifugal/examples/blob/master/tornado_application/code.html#L153 as reference

**Comment by nitin302** [comment]
Thanks for the reply. I will try this out.

**Comment by nitin302** [comment]
This works perfectly without any issues. Thanks for the help.

**Comment by easyyu** [comment]
> 
> 
> This works perfectly without any issues. Thanks for the help.

Hello.
Can you please give me the true example he did you achieve this?
If I have for example next to row:
```
client.publish("channels/%s/publish/%s" %(channelId,apiKey), "field1=" + str(Temp_OUT) + "&field2=" + str(Hum_OUT) + "&field3=" + str(Press_OUT) + "&field4=" + str(Illuminance) + "&field5=" + str(Temp_IN) + "&field6=" + str(Hum_IN) + "&field8=" + str(Temp_heat))
client.publish("channels/%s/publish/%s" %(channelId_air_quality,apiKey_Dornbirn_Air), "field1=" + str(PM25_air_quality) + "&field2=" + str(PM10_air_quality))
```
...then what is the right way to merge this two line in one?
Thank you.
