### ISSUE TITLE
Move javascript client to its own repo

### ISSUE THREAD

**Issue by FZambia** [centrifugal/centrifuge#51]
for the great good

**Comment by flc** [comment]
please consider creating a bower package

**Comment by FZambia** [comment]
@flc yep, of course

**Comment by FZambia** [comment]
Javacript client and plugins migrated to https://github.com/centrifugal/centrifuge-js repository. I'll update examples/docs soon and then `javascript` folder of this repo will be removed.

**Comment by FZambia** [comment]
done

**Comment by flc** [comment]
thanks, it was a very useful move, keep up the great work!

**Comment by FZambia** [comment]
at moment I work on Centrifuge 0.7.0 in `private` branch - there are some important changes and features - the most important is new Pusher-like private channel mechanism

**Comment by flc** [comment]
cool, can't wait
