### ISSUE TITLE
Passing headers

### ISSUE THREAD

**Issue by RakkFourkites** [centrifugal/centrifuge#52]
Hello ,How to pass authorisation headers from the client side when subscribing or publishing message?

**Comment by FZambia** [comment]
You can't pass headers on individual call - in websocket case you can only pass headers on initial connect. Then you have access to those headers on server side. Which client library you are using?

**Comment by RakkFourkites** [comment]
centrifuge-js is the client library

**Comment by FZambia** [comment]
Then you can only rely on browser which passes cookie set for domain. Browser Websocket implementation does not allow to set custom headers for WebSocket upgrade request. On server side you can access initial request and its headers over `Transport` - see https://godoc.org/github.com/centrifugal/centrifuge#TransportInfo

You can also provide custom connect data using `setConnectData` method on client side which you can access in `ClientConnecting` handler. Also you can use url params for some data theoretically and access them over initial request too. And it's possible to use JWT. Many options - just choose which one fits you better.

**Comment by RakkFourkites** [comment]
Ok thank you! :-)

**Comment by RakkFourkites** [comment]
Which method in ClientConnecting handler can be used to access the setConnectData passed from the client?

**Comment by FZambia** [comment]
https://godoc.org/github.com/centrifugal/centrifuge#ConnectEvent - it's a `Data` field of ConnectEvent you receive in handler.

**Comment by RakkFourkites** [comment]
Ok thank you so much! :-)

**Comment by RakkFourkites** [comment]
I have received the credentials from client using the clientConnecting handler.How to prevent a client from connecting to node in context of giving wrong credentials

**Comment by FZambia** [comment]
There are a bunch of ready to use disconnect objects you can return in [ConnectReply](https://godoc.org/github.com/centrifugal/centrifuge#ConnectReply) - you can choose one from available or create your own `Disconnect`. Looks like I need to add some description on which code numbers to use for custom Disconnects. Built-in codes start from `3000`, I suppose if you want to create custom one you need to use codes in range `4000-4999`.

**Comment by RakkFourkites** [comment]
Ok thank you very much! :-)
