### ISSUE TITLE
History 

### ISSUE THREAD

**Issue by RakkFourkites** [centrifugal/centrifuge#54]
Hi,A client when subscribing to a channel needs to get last n messages published in that channel.
How can I handle this use case?Any reference for that?
centrifuge-js is the client library I am using.

**Comment by FZambia** [comment]
Current client API allows to get all messages in history using `history` method of Subscription. History size is limited by server configuration for channel namespace. Do you need history on server or client side? Have you tried sth and came across a problem?

**Comment by RakkFourkites** [comment]
Hi thanks.I want to clear the events in centrifuge js each time.Every time i connect and disconnect,the events object of centrifuge is getting expanded.I want it to contain one connect or disconnect event at a time.i.e when i disconnect the previous disconnect events need not be maintained and same for connect events too.

**Comment by FZambia** [comment]
Sorry, I don't understand what you mean. You asked about history, now you are talking about clearing some sort of events. I need more context.

**Comment by RakkFourkites** [comment]
sorry,i tried to ask another doubt in same issue instead of creating a new one.

**Comment by RakkFourkites** [comment]
Are there any reference for how to use the history method of subscription?

**Comment by RakkFourkites** [comment]
i need to access history from client side.

**Comment by FZambia** [comment]
https://github.com/centrifugal/centrifuge-js#history-method-of-subscription

**Comment by RakkFourkites** [comment]
Thank you!I am sending the history data through ChannelInfo header in SubscribeReply .
How can i access data in client side?

**Comment by FZambia** [comment]
History contains last Publications published into channel. It's not related to Channel Info.  Channel Info is not exposed to client over current API - its appended to presence information and join/leave messages. As I said above you need to provide full context to me so I could understand what you are trying to achieve.

**Comment by RakkFourkites** [comment]
Ok the context is:
When a client subscribes to a channel ,he must be able to see the messages previously published to that channel(i.e history).
As you mentioned ,for the history method of subscription ,what is the server side handler?
For example,when we call publish from client,we are handling it using client.On().Publish() in the server side.Similarly how to handle history method of client in server?

**Comment by FZambia** [comment]
History extracted automatically from `HistoryManager` (from memory or from Redis), there is no server-side handler for this call.

So what you need is to pass some extra information to client when it subscribes to channel, right? Are you planning to get last messages from your main database? Why current `history` method does not fit your needs?

**Comment by RakkFourkites** [comment]
var sub = centrifuge.subscribe(channel, handleMessage)
                        .on("join", handleJoin)
                        .on("leave", handleLeave)
                        .on("unsubscribe", handleUnsubscribe)
                        .on("subscribe", handleSubscribe)
                        .on("error", handleSubscribeError);

sub.history().then(function(message) {
                        console.log(message);
                    },function(err) {
                        console.log("No history received");
                    });

**Comment by RakkFourkites** [comment]
that was a snippet of what i am trying.
I am not getting any message inside the callback of history.
Neither do i get the error message.

**Comment by RakkFourkites** [comment]
Thanks i have received the object. :-)

**Comment by RakkFourkites** [comment]
The history method is actually retrieving when the channel namespace in server side has a root name like this:
cfg.Namespaces = []centrifuge.ChannelNamespace{
		centrifuge.ChannelNamespace{
			Name: "chat",
			ChannelOptions: centrifuge.ChannelOptions{
				Publish:         true,
				JoinLeave:       true,
				Presence:        true,
				HistoryLifetime: 60,
				HistorySize:     1000,
				HistoryRecover:  true,
			},
		},
	}
But history is not working if I leave the name to be empty string .Is there a way to resolve this?

**Comment by RakkFourkites** [comment]
I am keeping this way, so that i can enter any channel name.But history is not working for this.It's always showing as "No message received".

cfg.Namespaces = []centrifuge.ChannelNamespace{
centrifuge.ChannelNamespace{
Name: "",
ChannelOptions: centrifuge.ChannelOptions{
Publish: true,
JoinLeave: true,
Presence: true,
HistoryLifetime: 60,
HistorySize: 1000,
HistoryRecover: true,
},
},
}

Should i always have a channel name i.e common root prefix for history to work?

**Comment by FZambia** [comment]
@RakkFourkites no, you can define the same options on config top level outside of `Namespaces`:

```
cfg.Publish =true
cfg.HistoryLifetime = 300
cfg.HistorySize = 100
... 
```
This way you don't need prefix. But I'd go with namespace prefix because this allows to configure your channels in a more flexible way as your app functionality grows. If you add new feature that does not need history for example you anyway may want to use new namespace to disable history in it.

**Comment by RakkFourkites** [comment]
Ok Thank you! :-)
