### ISSUE TITLE
'auth url address' response status code for deny

### ISSUE THREAD

**Issue by flc** [centrifugal/centrifuge#55]
It would make sense to respond from the 'auth url address' with 403 (forbidden) status code when a subscribe is not allowed to a channel however for some reason this results in an exception in https://github.com/centrifugal/centrifuge/blob/master/centrifuge/client.py#L321 and therefor the 'auth url address' gets called 'max auth attempts' times instead of just deny the access for the client after the first call.

I realized that I could respond with any !=200 status code and it would result in a deny but it feels a bit unnatural.

from the log:
```
[I 150118 01:52:21 client:325] error fetching auth address http://127.0.0.1:8000/auth-check/
[D 150118 01:52:21 client:326] HTTP 403: FORBIDDEN
[I 150118 01:52:21 client:325] error fetching auth address http://127.0.0.1:8000/auth-check/
[D 150118 01:52:21 client:326] HTTP 403: FORBIDDEN
```

**Comment by FZambia** [comment]
I agree. It seems that I thought 403 response code does not cause exception to be raised here.

**Comment by FZambia** [comment]
I have done some changes in a 0ce1028539893240494484a9de41db85099dc4b7 - what do you think?

**Comment by flc** [comment]
It seems to work so I think this will do for now. Thank you for your quick reactions!

**Comment by FZambia** [comment]
You are welcome! I uploaded new release on Pypi - `0.6.2`
