### ISSUE TITLE
Support for WSS?

### ISSUE THREAD

**Issue by nitin302** [centrifugal/centrifuge#57]
I'm trying to implement WSS with https pages: https://stackoverflow.com/questions/9745249/html5-websocket-with-ssl

How can i do this?

**Comment by nitin302** [comment]
I think, we should just change the connection string to "wss://". This seems to working with https connections.

**Comment by FZambia** [comment]
You need to start HTTP server with TLS certificates - see https://gist.github.com/denji/12b3a568f092ab951456 as example
