### ISSUE TITLE
configurable tornado HTTPServer params?

### ISSUE THREAD

**Issue by flc** [centrifugal/centrifuge#59]
@FZambia  what do you think would the best approach to make `tornado.httpserver.HTTPServer` init parameters (http://www.tornadoweb.org/en/stable/httpserver.html#tornado.httpserver.HTTPServer) configurable when starting centrifuge? for example since the recommended way to run centrifuge is behind a reverse proxy, setting the `xheaders` kwarg to `True` would make sense. introducing optional command line options to every one of them would be crazy. probably via the config file similar to `sockjs_settings`? like `tornado_settings` ?

**Comment by FZambia** [comment]
Hello! I like `tornado_settings` approach - it's simple and most options fit nice to JSON format, it seems that there is only 1 of them differs  - `io_loop` but I think we will be able to use `namedAny` (https://github.com/centrifugal/centrifuge/blob/master/centrifuge/utils.py#L153) in future to set it too from string if someone needs it.

**Comment by flc** [comment]
ok, i'll try to send a pull request soon...

**Comment by FZambia** [comment]
thanks for your contributing, this is available in v0.6.3 - already on Pypi

**Comment by flc** [comment]
got some "Build failed in Jenkins" emails but I don't think it has anything to do with the recent commits.
feel free to close if you think...

**Comment by FZambia** [comment]
wow! It's our corporate Jenkins, it turns out that it sends emails to all developers, sorry))
