### ISSUE TITLE
Add data to  client publish data

### ISSUE THREAD

**Issue by OrlandoCo** [centrifugal/centrifuge#60]
Hello, is there a way to add data to client published message?

**Comment by FZambia** [comment]
Hello, you can publish any payload you need - just be sure it can be encoded into JSON if you are using JSON protocol.

**Comment by OrlandoCo** [comment]
Hello I know I can publish any payload on the client, I mean on the server, I want to add a timestamp from the server to the payload.

**Comment by FZambia** [comment]
That's why you need to properly describe your problem in issues:) As an option you can call RPC from client and construct proper message on server side, then publish it into channel. Will this work for you?

**Comment by OrlandoCo** [comment]
I can make it work, I expected something more straightforward like:

`
client.On().Publish(func(e centrifuge.PublishEvent) centrifuge.PublishReply {
         //function to modify the Data
         modData(e);
         //emit the  data
         return centrifuge.PublishReply{e}
})
`
Obvioulsy the above code makes no sense it's an example, some libraries like socket.io or signalR works this way.

**Comment by FZambia** [comment]
So you mean sth like this:

```go
client.On().Publish(func(e centrifuge.PublishEvent) centrifuge.PublishReply {
    // function to modify the Data
    data := modData(e.Data);
    // emit the data
    return centrifuge.PublishReply{Data: data}
})
```

Right?

**Comment by OrlandoCo** [comment]
That's totally what I mean.

**Comment by FZambia** [comment]
Please check out pr #61
