### ISSUE TITLE
How to authentication Credentials use session value on revel framework

### ISSUE THREAD

**Issue by uugaa** [centrifugal/centrifuge#62]

**Comment by FZambia** [comment]
Hello. I don't know because I never used Revel. Have you already tried something?

**Comment by Alkanna** [comment]
Stuck on the same issue with gin, I got no idea how to access session values in centrifuge.

**Comment by FZambia** [comment]
@Alkanna hello, please provide examples on what you mean - what is session values, what you are trying to achieve etc. This library never took into account existing frameworks and generally follows Go standard HTTP library approach without introducing new concepts and abstractions on top of it.

**Comment by Alkanna** [comment]
Hey, @FZambia @uugaa I managed to find a solution to be able to access gin session inside an auth middleware for centrifuge.

`//At the resolver level we only have access to context.Context inside centrifuge, but we need the gin context
//So we create a gin middleware to add its context to the context.Context used by centrifuge websocket server
func GinContextToContextMiddleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		ctx := context.WithValue(c.Request.Context(), "GinContextKey", c)
		c.Request = c.Request.WithContext(ctx)
		c.Next()
	}
}

//We recover the gin context from the context.Context struct where we added it just above
func GinContextFromContext(ctx context.Context) (*gin.Context, error) {
	ginContext := ctx.Value("GinContextKey")
	if ginContext == nil {
		err := fmt.Errorf("could not retrieve gin.Context")
		return nil, err
	}
	gc, ok := ginContext.(*gin.Context)
	if !ok {
		err := fmt.Errorf("gin.Context has wrong type")
		return nil, err
	}
	return gc, nil
}

//Finally we can use gin context in the auth middleware of centrifuge!
func authMiddleware(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		//We get gin ctx from context.Context struct
		gc, err := GinContextFromContext(ctx)
		if err != nil {
			fmt.Printf("%s Failed to retrieve gin context", aurora.Red("[Error]"))
			return
		}
		//And now we can access gin session!
		s := sessions.Default(gc)
		username := s.Get("Username").(string)
		if username != "" {
			fmt.Printf("%s Successful websocket auth for user %s\n", aurora.Green("[Debug]"), aurora.Blue(username))
		} else {
			fmt.Printf("%s Failed websocket auth for user %s\n", aurora.Red("[Debug]"), aurora.Blue(username))
		}
		var newCtx context.Context
		r = r.WithContext(newCtx)
		h.ServeHTTP(w, r)
	})
}`

**Comment by FZambia** [comment]
@Alkanna makes sense, though I don't understand this place:

```
var newCtx context.Context
r = r.WithContext(newCtx)
h.ServeHTTP(w, r)
```

I suppose that the goal here is to set correct Credentials for Centrifuge? Then I suppose it should look like this:

```
newCtx := centrifuge.SetCredentials(ctx, &centrifuge.Credentials{
    UserID:   s.Get("UserID").(string),
})
r = r.WithContext(newCtx)
h.ServeHTTP(w, r)
```

Right?

**Comment by Alkanna** [comment]
Yep, I removed part of the code and forgot this bit, but this is indeed where I set the credentials acording to what was in the gin session.

**Comment by FZambia** [comment]
@Alkanna maybe you can contribute an example into our `_examples` folder with simple Gin app and integration with it session mechanism? Gin is quite popular so this can be helpful for future  library users.

**Comment by Alkanna** [comment]
I will make a pull request tomorrow or the day after for this :)

**Comment by Alkanna** [comment]
#68 Made the PR :)

**Comment by FZambia** [comment]
@Alkanna thanks! Will take a look after this weekend

**Comment by Alkanna** [comment]
I believe this can be closed @FZambia
