### ISSUE TITLE
Set Client.user w/o Disconnect/Connect events

### ISSUE THREAD

**Issue by jekaspekas** [centrifugal/centrifuge#76]
Hello!
I implement the user authentication process completely with WebSockets.
As I understand it, changing Client.user now is possible only at node.On().ClientConnecting method (by return Credentials at ConnectReply struct).
But Singin reguest is possible only after the Connecting event. And for add UserID to Client.user i have emit Disconnect/Connect events. I would like to avoid this.
Is it possible to add Client.SetUserID method like this:
```go
// SetUserID set user ID.
func (c *Client) SetUserID(userID string) {
	c.mu.Lock()
	c.user = userID
	c.mu.Unlock()
}
```
P.S.: I have studied the source code and did not see difficulty when applying sharding with Client.SetUserID method.

**Comment by FZambia** [comment]
Hello, could you provide more details on what you do? I don't want to introduce setter like this as user authentication must be done once on connection start and user ID can't be changed later. Maybe this is somehow related to https://github.com/centrifugal/centrifuge/pull/38 - but I really need more details to understand use case.

**Comment by jekaspekas** [comment]
Yes of course. Here is the centrifuge server config:
```go
	cfg := centrifuge.DefaultConfig
	cfg.Secret = "something"
	cfg.Publish = true
	cfg.Namespaces = []centrifuge.ChannelNamespace{
		centrifuge.ChannelNamespace{
			Name: "client",
			ChannelOptions: centrifuge.ChannelOptions{
				//Anonymous:       true,
				//Publish:         true,
				//JoinLeave:       true,
				//Presence:        true,
				HistorySize:     1000,
				HistoryLifetime: 60,
				HistoryRecover:  true,
			},
		},
	}
```

On client side:
```js
	let centrifuge = new Centrifuge('wss://localhost:443/connection/websocket?format=protobuf');
	const jwt = localStorage.getItem('jwt');
	if (jwt) {
		centrifuge.setToken(jwt);
	}
	centrifuge.connect();
```
When the user is not authenticated Token is not in the localStorage. Token is jwt with Issuer = UserID.
Next server Connection event handler:
```go
	node.On().ClientConnecting(func(ctx context.Context, t centrifuge.TransportInfo, e centrifuge.ConnectEvent) centrifuge.ConnectReply {
		userUUID, err := FuncConnecting(e)
		if err != nil {
			return centrifuge.ConnectReply{
				Credentials: &centrifuge.Credentials{
					ExpireAt: time.Now().Unix() + 1200,
				},
			}
		}
		return centrifuge.ConnectReply{
			Credentials: &centrifuge.Credentials{
				UserID:   userUUID.String(),
				ExpireAt: time.Now().Unix() + 3600,
			},
		}
	})
```
Where the FuncConnecting handles Token and checks for the existence UserID. Connection is established anyway.
Next step is Signin request from client side with login/password. As a result of successful authentication, the token must be sent to the client and on the server side UserID must be registered at Client.user.
At Signout request Client.user must be set to "".

**Comment by FZambia** [comment]
But what is the problem to simply reconnect on sign in an sign out? This looks natural to do.

**Comment by jekaspekas** [comment]
In this case, reconnect does not look natural to me.
Knowing that the centrifuge stores the UserID, I intuitively tried to find a suitable method in the documentation. But there is no such method. And instead of authenticating the user in two actions, i have to add two more.
In addition, unfortunately, I do not know all the intricacies associated with a websocket connection and cannot predict what interval is required between disconnect and connect events and what errors may occur.

**Comment by FZambia** [comment]
When user authenticates Centrifuge [adds it to client registry](https://github.com/centrifugal/centrifuge/blob/master/client.go#L1284). Adding a possibility to change user ID dynamically will require removing all its previous entries from connections list. Also references to user ID can be saved in client code inside event handlers - so it's pretty error prone functionality. Also I think it will drastically complicate adding new features in future as we should always remember about possibility of user ID modification. Every connection must belong to user known from start. I never saw a system where authentication happens in the middle of session - it always happens on start. So no – sorry but I won't accept feature like this.

**Comment by jekaspekas** [comment]
OK, thanks for answer
