### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by recoilme** [centrifugal/centrifuge#8]
try with 
```
git clone https://github.com/centrifugal/centrifuge.git
dep ensure 
```
with no luck(
it clones to centrifuge but depend from centrifugal/centrifuge
Must i clone all projects? Witch branches?

**Comment by recoilme** [comment]
luck with:
```
go get github.com/centrifugal/centrifuge
/// many errors about prometheus and so, just ignore them
cd github.com/centrifugal/centrifuge
dep ensure
```

**Comment by FZambia** [comment]
Clone into `$GOPATH/src/centrifugal/centrifuge`. This is what we have until Go get rid of GOPATH with `vgo`.

**Comment by recoilme** [comment]
That's not go/vgo/gopath problem. But ok, i close this
